version: '2'
services:
  wirvsvirus-app:
    image: wirvsvirus
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://wirvsvirus-mysql:3306/wirvsvirus?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  wirvsvirus-mysql:
    extends:
      file: mysql.yml
      service: wirvsvirus-mysql
